<?php

#### Generated by Block Creator by Disipal Site (www.disipal.net) ###
#### Enhanced by thainuke (www.thainuke.net) ###

if ( !defined('BLOCK_FILE') ) {
    Header("Location: ../index.php");
    die();
}
global $prefix, $multilingual, $currentlang, $db, $boxTitle, $content2, $pollcomm, $user, $cookie, $userinfo;

$content  =  "<table width=\"100%\" border=\"0\" cellspacing=\"2\" cellpadding=\"5\">";
$content  .= " <tr>";
$content  .= "   <td colspan=\"5\" align=\"center\"><a href=\"http://infodept.cattelecom.com/kasikorn/index.php\" target=\"_balnk\"><img height=\"80\" src=\"./images/logo_kasikorn.gif\" width=\"460\" border=\"1\" /></a></td>";
$content  .= " </tr>";
$content  .= " <tr>";
$content  .= "   <td colspan=\"5\" align=\"center\" style=\"padding:2px 0px 2px 0px; border-bottom:1px dotted #C0C0C0\">&nbsp;</td>";
$content  .= " </tr>";
$content  .= " <tr>";
$content  .= "   <td width=\"12%\" align=\"center\" valign=\"top\"><img height=\"82\" src=\"images/Img_highlight3.jpg\" width=\"138\" align=\"middle\" border=\"0\" /></td>";
$content  .= "   <td width=\"32%\" align=\"left\" valign=\"top\"><strong><img src=\"./images/arrowT.gif\" width=\"11\" height=\"9\" /> คู่มือการใช้งานระบบการติดตามแผนงาน/โครงการ</strong><br>";
$content  .= "     Ver. 4 - Update 11 สิงหาคม 2548<br>";
$content  .= "     <br>";
$content  .= "     <img src=\"./images/download.gif\" alt=\"Download\" width=\"28\" height=\"28\" border=\"0\" align=\"absmiddle\" /> <a href=\"http://infodept.cattelecom.com/images2/Displaynew_4.pdf\">Click here to download</a></td>";
$content  .= "   <td width=\"1%\" align=\"left\" valign=\"top\"  style=\"padding:2px 0px 2px 0px; border-right:1px dotted #C0C0C0\">&nbsp;</td>";
$content  .= "   <td width=\"12%\" align=\"left\" valign=\"top\"><img height=\"85\" src=\"images/Img_highlight2.jpg\" width=\"143\" align=\"middle\" border=\"0\" /></td>";
$content  .= "   <td width=\"43%\" align=\"left\" valign=\"top\"><strong><img src=\"./images/arrowT.gif\" width=\"11\" height=\"9\" /> คู่มือการใช้งานระบบสารสนเทศเพื่อผู้บริหาร   (EIS/MIS)</strong><br>";
$content  .= "     <br>";
$content  .= "     <img src=\"./images/download.gif\" alt=\"Download\" width=\"28\" height=\"28\" border=\"0\" align=\"absmiddle\" /> <a href=\"./eisweb/user_manual.htm\" target=\"_blank\">Click here to download</a></td>";
$content  .= " </tr>";
$content  .= " <tr>";
$content  .= "   <td colspan=\"5\" align=\"center\" style=\"padding:2px 0px 2px 0px; border-bottom:1px dotted #C0C0C0;border-top:1px dotted #C0C0C0\">&nbsp;</td>";
$content  .= " </tr>";
$content  .= " <tr>";
$content  .= "   <td align=\"center\" valign=\"top\"><img height=\"130\" src=\"images/java.gif\" width=\"100\" align=\"middle\" border=\"0\" /></td>";
$content  .= "   <td align=\"left\" valign=\"top\"><strong><img src=\"./images/arrowT.gif\" width=\"11\" height=\"9\" /> โปรแกรม Java</strong><br>";
$content  .= "     <br>";
$content  .= "     <img src=\"./images/publish_f2.png\" width=\"28\" height=\"28\" align=\"absmiddle\" /> <a href=\"./uploads/Files/installjava_manual.pdf\">ดาวน์โหลดคู่มือการติดตั้ง</a> <br>";
$content  .= "     <img src=\"./images/download.gif\" alt=\"Download\" width=\"28\" height=\"28\" border=\"0\" align=\"absmiddle\" /> <a href=\"./eisweb/msjavx86.exe\" target=\"_blank\">Click here to download</a></td>";
$content  .= "   <td align=\"left\" valign=\"top\"   style=\"padding:2px 0px 2px 0px; border-right:1px dotted #C0C0C0\">&nbsp;</td>";
$content  .= "   <td align=\"left\" valign=\"top\"><img src=\"./images/img_data_warehouse.gif\" width=\"135\" height=\"103\"></td>";
$content  .= "   <td align=\"left\" valign=\"top\"><strong><img src=\"./images/arrowT.gif\" width=\"11\" height=\"9\" /> คู่มือการใช้งานระบบ Datawarehouse / Data Mining</strong><br>";
$content  .= "     <br>";
$content  .= "     <img src=\"./images/publish_f2.png\" alt=\"\" width=\"28\" height=\"28\" align=\"absmiddle\" /> <a href=\"./usermanual/DW-DM/User Manual for setup SAS Microsoft Office Add-In.pdf\"  target=\"_blank\">คู่มือการติดตั้ง SAS Microsoft Add In</a><br>";
$content  .= "     <img src=\"./images/download.gif\" alt=\"Download\" width=\"28\" height=\"28\" border=\"0\" align=\"absmiddle\" /> <a href=\"./usermanual/DW-DM/SAS-Microsoft-AddIn.zip\" target=\"_blank\">ดาวน์โหลดโปรแกรม SAS Microsoft Add In</a><br>";
//$content  .= "     <img src=\"./images/publish_f2.png\" alt=\"\" width=\"28\" height=\"28\" align=\"absmiddle\" /> <a href=\"./eisweb/user_manual.htm\" target=\"_blank\">คู่มือการติดตั้ง SAS Enterprise Guide (E-Guide)</a><br>";
//$content  .= "     <img src=\"./images/publish_f2.png\" width=\"28\" height=\"28\" align=\"absmiddle\" /> <a href=\"./eisweb/user_manual.htm\" target=\"_blank\">คู่มือการใช้งาน Module BSC</a><br>";
//$content  .= "     <img src=\"./images/publish_f2.png\" width=\"28\" height=\"28\" align=\"absmiddle\" /> <a href=\"./eisweb/user_manual.htm\">คู่มือการใช้งาน Module FI</a><br>";
//$content  .= "     <img src=\"./images/publish_f2.png\" alt=\"\" width=\"28\" height=\"28\" border=\"0\" align=\"absmiddle\" /> <a href=\"./eisweb/user_manual.htm\">คู่มือการใช้งาน Module CM</a><br>";
//$content  .= "     <img src=\"./images/publish_f2.png\" alt=\"\" width=\"28\" height=\"28\" border=\"0\" align=\"absmiddle\" /> <a href=\"./eisweb/user_manual.htm\">คู่มือการใช้งาน Module NUA</a><br></td>";
$content  .= " </tr>";
$content  .= " <tr>";
$content  .= "   <td colspan=\"5\" align=\"center\" style=\"padding:2px 0px 2px 0px;border-top:1px dotted #C0C0C0\">&nbsp;</td>";
$content  .= " </tr>";
$content  .= "</table>";

?>